=== micronaut-projects/micronaut-guides/guide_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "minimumJavaVersion": {
            "type": "integer"
        },
        "prerequesites": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "clouds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skipGradleTests": {
            "type": "boolean"
        },
        "intro": {
            "type": "string"
        },
        "skipMavenTests": {
            "type": "boolean"
        },
        "features": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "publicationDate": {
            "type": "string"
        },
        "asciidoctor": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "buildTools": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "testFramework": {
            "type": "string"
        },
        "zipIncludes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "slug": {
            "type": "string"
        },
        "publish": {
            "type": "boolean"
        },
        "title": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "maximumJavaVersion": {
            "type": "integer"
        },
        "base": {
            "type": "string"
        },
        "env": {
            "type": "object",
            "properties": {
                "AWS_SECRET_ACCESS_KEY": {
                    "type": "string"
                },
                "AWS_REGION": {
                    "type": "string"
                },
                "AWS_ACCESS_KEY_ID": {
                    "type": "string"
                }
            }
        },
        "apps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "invisibleFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "kotlinFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "validateLicense": {
                        "type": "boolean"
                    },
                    "testFramework": {
                        "type": "string"
                    },
                    "javaFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "framework": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "features": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "packageName": {
                        "type": "string"
                    },
                    "excludeTest": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applicationType": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-graalpy-python-package/metadata.json
{
  "title": "Creating a Micronaut GraalPy application using a Python package",
  "intro": "Learn how to create a simple Micronaut GraalPy application using a third-party Python package.",
  "authors": ["Tomas Stupka"],
  "tags": ["junit"],
  "languages": ["JAVA"],
  "buildTools": ["MAVEN"],
  "categories": ["GraalPy"],
  "skipMavenTests": true,
  "publicationDate": "2024-07-01",
  "apps": [
    {
      "name": "default",
      "invisibleFeatures": ["graalpy-pygal"],
      "features": ["graalpy"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/buildSrc/src/test/resources/metadata-diff.json
{
  "title": "Publishing and subscribing to MQTT Topics from a Micronaut Application",
  "intro": "Learn how to use Mosquitto as an MQTT broker, create a Micronaut CLI application and publish an MQTT topic, and subscribe to the MQTT topic in a different Micronaut Messaging application.",
  "authors": ["Sergio del Amo"],
  "tags": ["messaging"],
  "categories": ["MESSAGING"],
  "publicationDate": "2022-03-14",
  "apps": [
    {
      "applicationType": "MESSAGING",
      "name": "app",
      "features": ["yaml","graalvm", "mqtt"],
      "javaFeatures": [ "awaitility"],
      "kotlinFeatures": [ "awaitility"]
    },
    {
      "applicationType": "CLI",
      "name": "cli",
      "features": ["yaml","graalvm", "mqtt"],
      "javaFeatures": [ "awaitility"],
      "kotlinFeatures": [ "awaitility", "kapt"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-data-mariadb-geospatial-nearby-drivers/metadata.json
{
  "title": "Find Nearby Delivery Drivers with Micronaut Data JDBC and MariaDB Geospatial",
  "intro": "Learn how to use Micronaut Data JDBC and MariaDB spatial queries to find the closest available delivery driver within 5 km of a food delivery order.",
  "authors": ["Milenko Supic"],
  "tags": ["database", "micronaut-data", "jdbc", "mariadb", "geospatial"],
  "categories": ["Data JDBC"],
  "languages": ["JAVA", "GROOVY", "KOTLIN"],
  "publicationDate": "2026-05-29",
  "apps": [
    {
      "name": "default",
      "excludeTest": ["DefaultTest"],
      "invisibleFeatures": ["jakarta-persistence-api", "test-resources-long-timeout"],
      "features": ["data-jdbc", "liquibase", "mariadb", "serialization-jackson", "validation"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/spring-boot-to-micronaut-at-configuration-at-bean-at-factory/metadata.json
{
  "title": "Manually define a Bean - Spring Boot",
  "intro": "This guide compares how to create a bean in a Spring Boot application with @Configuration vs. in a Micronaut application with @Factory.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Spring Boot"],
  "publicationDate": "2022-09-13",
  "languages": ["JAVA", "GROOVY"],
  "apps": [
    {
      "framework": "Spring Boot",
      "testFramework": "JUNIT",
      "name": "springboot",
      "features": ["spring-boot-starter-web"]
    },
    {
      "name": "micronautframework",
      "features": []
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-kotlin-extension-fns/metadata.json
{
  "asciidoctor": "micronaut-kotlin-extension-fns.adoc",
  "slug": "micronaut-kotlin-extension-fns",
  "title": "Using Kotlin Extension Functions in Micronaut",
  "intro": "Take a tour of the extension functions in Micronaut and learn to write your own",
  "authors": ["Will Buck"],
  "languages": ["kotlin"],
  "apps": [
    {
      "name": "default",
      "features": ["graalvm", "kotlin-extension-functions"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-graalpy/metadata.json
{
  "title": "Creating your first Micronaut GraalPy application",
  "intro": "Learn how to create a Hello World Micronaut GraalPy application with a controller and a functional test.",
  "authors": ["Tomas Stupka"],
  "tags": ["junit"],
  "languages": ["JAVA", "KOTLIN"],
  "buildTools": ["MAVEN", "GRADLE"],
  "categories": ["GraalPy"],
  "publicationDate": "2024-07-01",
  "apps": [
    {
      "name": "default",
      "features": ["graalpy"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/building-a-rest-api-spring-boot-vs-micronaut-security-basic-auth/metadata.json
{
  "title": "6. Security Basic Authentication - Spring Boot vs Micronaut Framework - Building a REST API",
  "intro": "This guide compares how to secure a REST API with basic authentication in Micronaut and Spring Boot applications.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Boot to Micronaut Building a REST API"],
  "publicationDate": "2024-04-29",
  "languages": ["JAVA"],
  "buildTools": ["GRADLE"],
  "apps": [
    {
      "framework": "Spring Boot",
      "name": "springboot",
      "features": ["spring-boot-starter-web", "h2", "spring-boot-data-jdbc", "spring-boot-starter-security"]
    },
    {
      "name": "micronautframework",
      "features": ["json-path", "assertj", "data-jdbc", "json-smart", "security", "spring-security-crypto"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/building-a-rest-api-spring-boot-vs-micronaut-get-list/metadata.json
{
  "title": "5. Paginated List - Spring Boot vs Micronaut Framework - Building a REST API",
  "intro": "This guide compares how to create a GET endpoint that returns a paginated JSON Array in Micronaut and Spring Boot applications.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Boot to Micronaut Building a REST API"],
  "publicationDate": "2024-04-28",
  "languages": ["JAVA", "KOTLIN"],
  "buildTools": ["GRADLE"],
  "apps": [
    {
      "framework": "Spring Boot",
      "name": "springboot",
      "features": ["spring-boot-starter-web", "h2", "spring-boot-data-jdbc"]
    },
    {
      "name": "micronautframework",
      "features": ["json-path", "assertj", "data-jdbc", "json-smart"]
    }
  ]
}
