=== micronaut-projects/micronaut-guides/guide_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "minimumJavaVersion": {
            "type": "integer"
        },
        "prerequesites": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "clouds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skipGradleTests": {
            "type": "boolean"
        },
        "intro": {
            "type": "string"
        },
        "skipMavenTests": {
            "type": "boolean"
        },
        "features": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "publicationDate": {
            "type": "string"
        },
        "asciidoctor": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "buildTools": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "testFramework": {
            "type": "string"
        },
        "zipIncludes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "slug": {
            "type": "string"
        },
        "publish": {
            "type": "boolean"
        },
        "title": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "maximumJavaVersion": {
            "type": "integer"
        },
        "base": {
            "type": "string"
        },
        "env": {
            "type": "object",
            "properties": {
                "AWS_SECRET_ACCESS_KEY": {
                    "type": "string"
                },
                "AWS_REGION": {
                    "type": "string"
                },
                "AWS_ACCESS_KEY_ID": {
                    "type": "string"
                }
            }
        },
        "apps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "invisibleFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "kotlinFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "validateLicense": {
                        "type": "boolean"
                    },
                    "testFramework": {
                        "type": "string"
                    },
                    "javaFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "framework": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "features": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "packageName": {
                        "type": "string"
                    },
                    "excludeTest": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applicationType": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-dependency-injection-types/metadata.json
{
  "title": "Micronaut Dependency Injection Types",
  "intro": "Constructor, field, and method parameter injection.",
  "authors": ["Sergio del Amo"],
  "tags": ["junit","di"],
  "categories": ["Core Basics"],
  "publicationDate": "2022-09-09",
  "testFramework": "JUNIT",
  "apps": [
    {
      "name": "default",
      "features": ["junit-params"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-crac-helloworld/metadata.json
{
  "title": "Micronaut CRaC",
  "intro": "Learn how to start using CRaC with a Micronaut application.",
  "authors": ["Sergio del Amo"],
  "tags": ["endpoint-info"],
  "categories": ["Coordinated Restore at Checkpoint"],
  "publicationDate": "2023-11-22",
  "languages": ["JAVA", "GROOVY"],
  "apps": [
    {
      "name": "default",
      "features": ["crac", "management"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-intellij-idea-ide-setup/metadata.json
{
  "title": "Using IntelliJ IDEA to develop Micronaut applications",
  "intro": "Delegate run and build actions to Gradle and Maven when working with IntelliJ IDEA",
  "authors": ["Sergio del Amo"],
  "tags": [],
  "categories": ["Development"],
  "publicationDate": "2023-02-13",
  "languages": ["JAVA", "KOTLIN"],
  "apps": [
    {
      "name": "default",
      "features": []
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-workshop-langchain4j-step-01/metadata.json
{
  "title": "Step 01 - Micronaut LangChain4j Workshop",
  "base": "micronaut-workshop-langchain4j",
  "intro": "Introduction to Micronaut LangChain4j",
  "authors": ["Sergio del Amo"],
  "languages": ["JAVA"],
  "categories": ["LANGCHAIN4J"],
  "publicationDate": "2026-02-12",
  "apps": [
    {
      "name": "default",
      "features": ["importmap","vaadin-webcomponents","es-module-shims","wc-chatbot","jax-rs", "micronaut-langchain4j-openai", "websocket", "reactor", "awaitility"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-oauth2-cognito/metadata.json
{
  "asciidoctor": "micronaut-oauth2-cognito.adoc",
  "slug": "micronaut-oauth2-cognito",
  "title": "Secure a Micronaut app with Cognito",
  "intro": "Learn how to create Micronaut app and secure it with an Authorization Server provided by Cognito.",
  "authors": ["Sergio del Amo"],
  "languages": ["java"],
  "apps": [
    {
      "name": "default",
      "features": ["graalvm", "views-thymeleaf", "security-jwt", "security-oauth2"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-graphql-chat/metadata.json
{
  "title": "Build a GraphQL chat application with Micronaut GraphQL",
  "intro": "Learn how to expose GraphQL queries, mutations, and subscriptions over graphql-ws with Micronaut GraphQL.",
  "authors": ["Graeme Rocher"],
  "tags": ["graphql", "websocket", "subscriptions"],
  "categories": ["GraphQL"],
  "publicationDate": "2026-04-29",
  "languages": ["JAVA"],
  "apps": [
    {
      "name": "default",
      "features": ["graphql", "websocket", "reactor", "serialization-jackson"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-langchain4j-openai-prompt-template/metadata.json
{
  "title": "Langchain4j OpenAI Prompt Template",
  "intro": "Langchain4j OpenAI Prompt Template",
  "authors": ["Sergio del Amo"],
  "tags": ["testcontainers"],
  "categories": ["AI"],
  "publicationDate": "2026-01-01",
  "languages": ["JAVA"],
  "apps": [
    {
      "excludeTest": ["DefaultTest"],
      "name": "default",
      "features": ["langchain4j-openai", "testcontainers", "validation", "problem-json"],
      "invisibleFeatures": ["wiremock-standalone"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-data-many-to-many-oracle/metadata.json
{
  "base": "micronaut-data-many-to-many-base",
  "title": "Many-to-Many with Micronaut Data JDBC and Oracle",
  "intro": "Learn how to map a many-to-many association with Micronaut Data JDBC and Oracle.",
  "authors": ["Sergio del Amo"],
  "tags": [],
  "categories": ["Database Modeling"],
  "languages": ["JAVA"],
  "publicationDate": "2025-11-12",
  "apps": [
    {
      "name": "default",
      "features": ["data-jdbc","liquibase","oracle", "validation"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}
