=== micronaut-projects/micronaut-guides/guide_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "minimumJavaVersion": {
            "type": "integer"
        },
        "prerequesites": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "clouds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skipGradleTests": {
            "type": "boolean"
        },
        "intro": {
            "type": "string"
        },
        "skipMavenTests": {
            "type": "boolean"
        },
        "features": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "publicationDate": {
            "type": "string"
        },
        "asciidoctor": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "buildTools": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "testFramework": {
            "type": "string"
        },
        "zipIncludes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "slug": {
            "type": "string"
        },
        "publish": {
            "type": "boolean"
        },
        "title": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "maximumJavaVersion": {
            "type": "integer"
        },
        "base": {
            "type": "string"
        },
        "env": {
            "type": "object",
            "properties": {
                "AWS_SECRET_ACCESS_KEY": {
                    "type": "string"
                },
                "AWS_REGION": {
                    "type": "string"
                },
                "AWS_ACCESS_KEY_ID": {
                    "type": "string"
                }
            }
        },
        "apps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "invisibleFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "kotlinFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "validateLicense": {
                        "type": "boolean"
                    },
                    "testFramework": {
                        "type": "string"
                    },
                    "javaFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "framework": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "features": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "packageName": {
                        "type": "string"
                    },
                    "excludeTest": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applicationType": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-workshop-langchain4j-step-02/metadata.json
{
  "title": "Step 02 - LLM configuration",
  "base": "micronaut-workshop-langchain4j",
  "intro": "In this step, we will play with various configurations of the language model (LLM) that we will use in the subsequent steps",
  "authors": ["Sergio del Amo"],
  "languages": ["JAVA"],
  "categories": ["LANGCHAIN4J"],
  "publicationDate": "2026-02-12",
  "apps": [
    {
      "name": "default",
      "features": ["importmap","vaadin-webcomponents","es-module-shims","wc-chatbot","jax-rs", "micronaut-langchain4j-openai", "websocket", "reactor", "awaitility"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/spring-boot-to-micronaut-uri-components-builder-vs-uri-builder/metadata.json
{
  "title": "Building URIs - Spring Boot",
  "intro": "This guide compares using Spring's UriComponentsBuilder vs Micronaut Framework's UriBuilder.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Spring Boot"],
  "publicationDate": "2022-09-13",
  "languages": ["JAVA", "KOTLIN"],
  "apps": [
    {
      "framework": "Spring Boot",
      "name": "springboot",
      "features": ["spring-boot-starter-web"]
    },
    {
      "name": "micronautframework",
      "features": []
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-push-to-github-container-registry/metadata.json
{
  "title": "Push a Docker image of a Micronaut application to GitHub Packages Container registry",
  "intro": "Learn how to push a Docker image of a Micronaut application to GitHub Packages Container registry",
  "authors": ["Sergio del Amo"],
  "tags": ["docker"],
  "categories": ["Registry"],
  "publicationDate": "2025-03-16",
  "buildTools": ["GRADLE"],
  "languages": ["JAVA"],
  "apps": [
    {
      "name": "default"
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-data-mongodb-asynchronous/metadata.json
{
  "title": "Access a MongoDB database asynchronously with Micronaut Data MongoDB and Reactive Streams",
  "intro": "Learn how to access a MongoDB database asynchronously with Micronaut Data.",
  "authors": ["Tim Yates"],
  "tags": ["database", "micronaut-data", "mongodb", "async"],
  "categories": ["MongoDB"],
  "publicationDate": "2022-05-05",
  "languages": ["JAVA", "GROOVY", "KOTLIN"],
  "apps": [
    {
      "name": "default",
      "features": ["data-mongodb-reactive", "reactor"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-mcp-diskspace-http/metadata.json
{
  "base": "micronaut-mcp-diskspace",
  "title": "Disk Space MCP Server with Streamable HTTP transport",
  "intro": "Build an MCP Server with Streamable HTTP transport to expose your machine disk space.",
  "authors": ["Sergio del Amo"],
  "languages": ["JAVA", "GROOVY"],
  "tags": [],
  "categories": ["MCP"],
  "publicationDate": "2026-01-11",
  "apps": [
    {
      "excludeTest": ["DefaultTest"],
      "name": "default",
      "features": ["mcp-http", "mcp-client-java-sdk"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-custom-validation-annotation/metadata.json
{
  "title": "Custom constraint annotation for validation",
  "intro": "Learn how to create a custom constraint annotation for validation in your Micronaut application.",
  "authors": ["Sergio del Amo"],
  "tags": ["validation"],
  "categories": ["Validation"],
  "publicationDate": "2023-02-13",
  "apps": [
    {
      "name": "default",
      "features": ["junit-params", "validation"]
    }
  ],
  "languages": ["JAVA", "KOTLIN"]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-security-session/metadata.json
{
  "title": "Session-based authentication",
  "intro": "Learn how to secure a Micronaut application using session-based authentication.",
  "authors": ["Sergio del Amo"],
  "tags": ["spock", "geb", "session", "security", "views", "velocity"],
  "categories": ["Micronaut Security"],
  "publicationDate": "2018-05-24",
  "testFramework": "SPOCK",
  "apps": [
    {
      "name": "default",
      "features": ["security-session", "views-velocity", "geb", "reactor"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-control-panel/metadata.json
{
  "title": "Micronaut Control Panel",
  "intro": "Learn how to add Micronaut Control Panel to a development application.",
  "authors": ["Micronaut Team"],
  "tags": ["control-panel", "development", "views"],
  "categories": ["Development"],
  "publicationDate": "2026-05-27",
  "languages": ["JAVA"],
  "apps": [
    {
      "name": "default",
      "features": ["control-panel-ui", "views-handlebars", "management"]
    }
  ]
}
