=== micronaut-projects/micronaut-guides/buildSrc/src/main/resources/META-INF/schemas/guide-metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "uri": "https://guides.micronaut.io/schemas",
  "type": "object",
  "required": ["title","intro","authors","categories","publicationDate"],
  "properties": {
    "title": {
      "description": "The guide's title",
      "type": "string"
    },
    "authors": {
      "description": "The guide's authors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "intro": {
      "description": "The guide introduction",
      "type": "string"
    },
    "publicationDate": {
      "description": "The guide publication date. It should follow the format YYYY-MM-DD",
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
    },
    "minimumJavaVersion": {
      "description": "If the guide needs a minimum Java version, define it here",
      "type": "integer"
    },
    "maximumJavaVersion": {
      "description": "If the guide needs a maximum Java version, define it here",
      "type": "integer"
    },
    "cloud": {
      "description": "The acronym for the cloud service provider of the guide. For example, OCI for Oracle Cloud Infrastructure",
      "type": "string",
      "enum": ["OCI","AWS","GCP","Azure"]
    },
    "skipGradleTests": {
      "description": "Set it to true to skip running the tests for the Gradle applications for the guide",
      "type": "boolean"
    },
    "skipMavenTests": {
      "description": "Set it to true to skip running the tests for the Maven applications for the guide",
      "type": "boolean"
    },
    "asciidoctor": {
      "description": "The guide asciidoc file. If not specified, the guide slug followed by the .adoc suffix is used",
      "type": "string"
    },
    "languages": {
      "description": "The guide supported languages",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["java","groovy","kotlin"]
      }
    },
    "tags": {
      "description": "List of tags added to the guide. features are added automatically as tags. No need to repeat them here", 
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "buildTools": {
      "description": "By default the code in the guide is generated for Gradle and Maven. If a guide is specific only for a build tool, define it here",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["maven","gradle", "gradle_kotlin"]
      }
    },
    "testFramework": {
      "description": "The guide's test framework. By default Java and Kotlin applications are tested with JUnit5 and Groovy applications with Spock",
      "type": "string",
      "enum": ["spock","junit"]
    },
    "zipIncludes": {
      "description": "List of additional files with a relative path to include in the generated zip file for the guide",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "categories": {
      "description": "The guide's categories",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "slug": {
      "description": "The guide's slug. If not specified, the guides folder is used.",
      "type": "string"
    },
    "publish": {
      "description": "Whether the guide should be published, it defaults to true. You can set it to false for draft or base guides.",
      "type": "boolean"
    },
    "base": {
      "description": "Defaults to null; if set, indicates directory name of the base guide to copy before copying the current one",
      "type": "string"
    },
    "env": {
      "description": "The guide's environment variables",
      "type": "object"
    },
    "apps": {
      "description": "Applications created for the guide.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The app's name. For single application guides, the application needs to be named default. ",
            "type": "string"
          },
          "packageName": {
            "description": "The app's package name. It you don't specify, the package name example.micronaut is used",
            "type": "string"
          },
          "applicationType": {
            "description": "The app type.  It you don't specify, default is used",
            "type": "string",
            "enum": ["default","cli","function","grpc","messaging"]
          },
          "framework": {
            "description": "The app's framework. Default is Micronaut but Spring Boot is also supported",
            "type": "string"
          },
          "features": {
            "description": "The Micronaut Starter features' name that the app requires",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "invisibleFeatures": {
            "description": "The app's invisible features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "kotlinFeatures": {
            "description": "The app's Kotlin features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "javaFeatures": {
            "description": "The app's Java features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "validateLicense": {
            "type": "boolean"
          },
          "testFramework": {
            "description": "The app's test framework",
            "type": "string"
          },
          "excludeTest": {
            "description": "The tests that should not be run",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-google-cloud-http-function/metadata.json
{
  "title": "Deploy an HTTP Function to Google Cloud Functions",
  "intro": "Deploy a Micronaut application as an HTTP Function to Google Cloud Functions, a scalable pay-as-you-go functions-as-a-service (FaaS) to run your code with zero server management.",
  "authors": ["Sergio del Amo"],
  "tags": ["cloudfunctions"],
  "categories": ["Serverless"],
  "cloud": "GCP",
  "publicationDate": "2021-10-19",
  "apps": [
    {
      "name": "default",
      "features": ["google-cloud-function"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/spring-boot-to-micronaut-replace-h2-with-real-database-for-testing/metadata.json
{
  "title": "Replace H2 with a real database for testing - Spring Boot to Micronaut Framework",
  "intro": "This guide shows compares how replace H2 with a real database for testing in a Spring Boot application vs a Micronaut Framework application.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Spring Boot to Micronaut Framework"],
  "publicationDate": "2023-08-01",
  "languages": ["java"],
  "apps": [
    {
      "framework": "Spring Boot",
      "testFramework": "junit",
      "name": "springboot",
      "features": ["spring-boot-starter-data-jpa", "postgresql-driver", "testcontainers-junit-jupiter", "spring-boot-testcontainers", "assertj"]
    },
    {
      "name": "micronautframework",
      "features": ["data-jpa", "testcontainers", "assertj", "postgresql"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-microservices-services-discover-consul/metadata.json
{
  "title": "Consul and the Micronaut Framework - Microservices Service Discovery",
  "intro": "Use Consul service discovery to expose your Micronaut applications.",
  "authors": ["Sergio del Amo"],
  "tags": ["consul", "validation", "service-discovery"],
  "categories": ["Service Discovery"],
  "publicationDate": "2018-07-27",
  "apps": [
    {
      "name": "bookcatalogue",
      "features": ["yaml","discovery-consul", "management", "serialization-jackson"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    },
    {
      "name": "bookinventory",
      "features": ["yaml","discovery-consul", "management", "serialization-jackson"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    },
    {
      "name": "bookrecommendation",
      "features": ["yaml","discovery-consul", "management", "reactor", "serialization-jackson","http-client","retry"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-produces-xml/metadata.json
{
  "title": "Render XML in a Micronaut Controller",
  "base": "hello-base",
  "intro": "Learn how to use Jackson to render XML in a Micronaut Controller.",
  "authors": ["Sergio del Amo"],
  "categories": ["Beyond the Basics"],
  "publicationDate": "2024-01-15",
  "languages": ["java"],
  "apps": [
    {
      "name": "default",
      "features": ["jackson-databind", "jackson-xml"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-oauth2-github/metadata.json
{
  "title": "Secure a Micronaut application with GitHub",
  "intro": "Learn how to create a Micronaut application and secure it with an Authorization Server provided by GitHub. Learn how to write your own Authentication Mapper.",
  "authors": ["Sergio del Amo"],
  "tags": ["oauth2", "github", "security"],
  "categories": ["Authorization Code"],
  "publicationDate": "2019-12-26",
  "apps": [
    {
      "name": "default",
      "features": ["views-thymeleaf", "security-oauth2", "security-jwt", "reactor", "serialization-jackson", "http-client"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-data-json-duality-view/metadata.json
{
  "title": "Use JSON duality view in Oracle",
  "intro": "Learn how to use JSON duality views in Micronaut",
  "authors": ["Dimitrije Zdravkovic"],
  "tags": ["database", "micronaut-data", "JSON duality view"],
  "categories": ["Data JDBC"],
  "publicationDate": "2025-01-21",
  "apps": [
    {
      "name": "default",
      "features": ["data-jdbc", "jdbc-hikari" ,"oracle", "serialization-jackson","validation"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-hashicorp-vault/metadata.json
{
  "asciidoctor": "micronaut-hashicorp-vault.adoc",
  "slug": "micronaut-hashicorp-vault",
  "title": "Distributed Configuration with Hashicorp Vault and Micronaut",
  "intro": "Learn how to load your secrets from Hashicorp Vault in your Micronaut application",
  "authors": ["Sergio del Amo", "Tim Yates"],
  "tags": ["hashicorp", "vault", "secrets"],
  "categories": ["Secrets Manager"],
  "publicationDate": "2019-05-16",
  "apps": [
    {
      "name": "default",
      "features": ["graalvm", "security-oauth2", "config-consul", "testcontainers"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/executable-jar/metadata.json
{
  "title": "Create an Executable JAR of a Micronaut application",
  "intro": "Learn how to generate an executable JAR of a Micronaut application with Maven or Gradle.",
  "authors": ["Sergio del Amo"],
  "tags": [],
  "base": "distribution-base",
  "categories": ["Distribution"],
  "publicationDate": "2022-09-16",
  "apps": [
    {
      "name": "default",
      "features": []
    }
  ]
}
