=== micronaut-projects/micronaut-guides/buildSrc/src/main/resources/META-INF/schemas/guide-metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "uri": "https://guides.micronaut.io/schemas",
  "type": "object",
  "required": ["title","intro","authors","categories","publicationDate"],
  "properties": {
    "title": {
      "description": "The guide's title",
      "type": "string"
    },
    "authors": {
      "description": "The guide's authors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "intro": {
      "description": "The guide introduction",
      "type": "string"
    },
    "publicationDate": {
      "description": "The guide publication date. It should follow the format YYYY-MM-DD",
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
    },
    "minimumJavaVersion": {
      "description": "If the guide needs a minimum Java version, define it here",
      "type": "integer"
    },
    "maximumJavaVersion": {
      "description": "If the guide needs a maximum Java version, define it here",
      "type": "integer"
    },
    "cloud": {
      "description": "The acronym for the cloud service provider of the guide. For example, OCI for Oracle Cloud Infrastructure",
      "type": "string",
      "enum": ["OCI","AWS","GCP","Azure"]
    },
    "skipGradleTests": {
      "description": "Set it to true to skip running the tests for the Gradle applications for the guide",
      "type": "boolean"
    },
    "skipMavenTests": {
      "description": "Set it to true to skip running the tests for the Maven applications for the guide",
      "type": "boolean"
    },
    "asciidoctor": {
      "description": "The guide asciidoc file. If not specified, the guide slug followed by the .adoc suffix is used",
      "type": "string"
    },
    "languages": {
      "description": "The guide supported languages",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["java","groovy","kotlin"]
      }
    },
    "tags": {
      "description": "List of tags added to the guide. features are added automatically as tags. No need to repeat them here", 
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "buildTools": {
      "description": "By default the code in the guide is generated for Gradle and Maven. If a guide is specific only for a build tool, define it here",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["maven","gradle", "gradle_kotlin"]
      }
    },
    "testFramework": {
      "description": "The guide's test framework. By default Java and Kotlin applications are tested with JUnit5 and Groovy applications with Spock",
      "type": "string",
      "enum": ["spock","junit"]
    },
    "zipIncludes": {
      "description": "List of additional files with a relative path to include in the generated zip file for the guide",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "categories": {
      "description": "The guide's categories",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "slug": {
      "description": "The guide's slug. If not specified, the guides folder is used.",
      "type": "string"
    },
    "publish": {
      "description": "Whether the guide should be published, it defaults to true. You can set it to false for draft or base guides.",
      "type": "boolean"
    },
    "base": {
      "description": "Defaults to null; if set, indicates directory name of the base guide to copy before copying the current one",
      "type": "string"
    },
    "env": {
      "description": "The guide's environment variables",
      "type": "object"
    },
    "apps": {
      "description": "Applications created for the guide.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The app's name. For single application guides, the application needs to be named default. ",
            "type": "string"
          },
          "packageName": {
            "description": "The app's package name. It you don't specify, the package name example.micronaut is used",
            "type": "string"
          },
          "applicationType": {
            "description": "The app type.  It you don't specify, default is used",
            "type": "string",
            "enum": ["default","cli","function","grpc","messaging"]
          },
          "framework": {
            "description": "The app's framework. Default is Micronaut but Spring Boot is also supported",
            "type": "string"
          },
          "features": {
            "description": "The Micronaut Starter features' name that the app requires",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "invisibleFeatures": {
            "description": "The app's invisible features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "kotlinFeatures": {
            "description": "The app's Kotlin features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "javaFeatures": {
            "description": "The app's Java features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "validateLicense": {
            "type": "boolean"
          },
          "testFramework": {
            "description": "The app's test framework",
            "type": "string"
          },
          "excludeTest": {
            "description": "The tests that should not be run",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-k8s-gcp/metadata.json
{
  "base": "micronaut-k8s",
  "title": "Service discovery and distributed configuration with Google Kubernetes Engine (GKE)",
  "intro": "Service discovery and distributed configuration in a Micronaut application with Google Kubernetes Engine (GKE)",
  "authors": ["Nemanja Mikic"],
  "tags": ["kubernetes", "service-discovery", "GKE"],
  "zipIncludes": ["api/k8s.yml", "orders/k8s.yml", "users/k8s.yml"],
  "categories": ["Kubernetes", "Service Discovery", "Distributed Configuration"],
  "cloud": "GCP",
  "publicationDate": "2023-09-12",
  "apps": [
    {
      "name": "users",
      "features": [],
      "packageName": "example.micronaut"
    },
    {
      "name": "orders",
      "features": [],
      "packageName": "example.micronaut"
    },
    {
      "name": "api",
      "features": [],
      "packageName": "example.micronaut"
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-azure-logging/metadata.json
{
  "title": "Publish Micronaut application logs to Microsoft Azure Monitor Logs",
  "intro": "Learn how to send your Micronaut application Logback logs to Microsoft Azure Monitor Logs.",
  "authors": ["Burt Beckwith"],
  "tags": ["azure", "cloud"],
  "categories": ["Microsoft Azure"],
  "publicationDate": "2024-08-22",
  "apps": [
    {
      "name": "default",
      "features": []
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/spring-boot-to-micronaut-testing-rest-api-integrations-using-mockserver/metadata.json
{
  "title": "Application Class - Spring Boot to Micronaut Framework",
  "intro": "This guide shows compares the Application Class of a Spring Boot application vs a Micronaut Framework application.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Spring Boot to Micronaut Framework"],
  "publicationDate": "2023-07-30",
  "languages": ["java"],
  "apps": [
    {
      "framework": "Spring Boot",
      "testFramework": "junit",
      "name": "springboot",
      "features": ["spring-boot-starter-web", "spring-boot-starter-webflux", "spring-boot-testcontainers", "mock-server", "rest-assured"]
    },
    {
      "name": "micronautframework",
      "features": ["http-client", "micronaut-test-rest-assured", "mock-server", "testcontainers-junit-jupiter"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/buildSrc/src/test/resources/guides/child/metadata.json
{
  "base": "base",
  "authors": ["Graeme Rocher"],
  "title": "Connect a Micronaut Data JDBC Application to Azure Database for MySQL",
  "intro": "Learn how to connect a Micronaut Data JDBC application to a Microsoft Azure Database for MySQL",
  "tags": ["Azure"],
  "categories": ["Data JDBC"],
  "publicationDate": "2022-02-17"
}

=== micronaut-projects/micronaut-guides/guides/spring-boot-to-micronaut-jooq-flyway-using-testcontainers/metadata.json
{
  "title": "Application Class - Spring Boot to Micronaut Framework",
  "intro": "This guide shows compares the Application Class of a Spring Boot application vs a Micronaut Framework application.",
  "authors": ["Sergio del Amo"],
  "tags": ["spring-boot"],
  "categories": ["Spring Boot to Micronaut Framework"],
  "publicationDate": "2022-09-13",
  "languages": ["java"],
  "buildTools": ["maven"],
  "apps": [
    {
      "framework": "Spring Boot",
      "testFramework": "junit",
      "name": "springboot",
      "features": ["spring-boot-starter-jooq", "flyway-core", "postgresql-driver", "spring-boot-testcontainers", "spring-boot-devtools", "testcontainers-jooq-codegen-maven-plugin.version"],
      "excludeTest": [
        "ApplicationTest"
      ]
    },
    {
      "name": "micronautframework",
      "features": ["flyway","jooq","postgres", "testcontainers", "assertj", "testcontainers-jooq-codegen-maven-plugin.version"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-google-cloud-platform-cloud-run/metadata.json
{
  "base": "hello-base",
  "title": "Deploy to Google Cloud Run",
  "intro": "Deploy a Micronaut application to Google Cloud Run, a fully managed serverless platform for containerized applications.",
  "authors": ["Sergio del Amo"],
  "tags": ["cloudrun"],
  "categories": ["Scale to Zero Containers"],
  "cloud": "GCP",
  "publicationDate": "2021-10-01",
  "apps": [
    {
      "name": "default",
      "features": ["docker-push-gcr"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-cloud-oidc-oracle/metadata.json
{
  "base": "micronaut-cloud-oidc-base",
  "authors": ["Burt Beckwith"],
  "title": "Authenticate Micronaut application users with OpenID Connect and Oracle IDCS",
  "intro": "Learn how to create a secured Micronaut application and authenticate with OpenID Connect in Oracle Cloud.",
  "tags": ["oracle"],
  "categories": ["Authorization Code"],
  "cloud": "OCI",
  "publicationDate": "2022-03-31"
}

=== micronaut-projects/micronaut-guides/guides/micronaut-oracle-email-delivery/metadata.json
{
  "title": "Oracle Cloud Infrastructure (OCI) Email Delivery using the Micronaut framework",
  "intro": "Learn how to send an email with Oracle Cloud Infrastructure (OCI) Email Delivery using the Micronaut framework.",
  "authors": ["Hari Krishna Sivvala","Burt Beckwith"],
  "tags": ["oracle", "cloud"],
  "categories": ["Email"],
    "cloud": "OCI",
  "publicationDate": "2022-05-17",
  "apps": [{
    "name": "default",
    "features": ["yaml","email-javamail","email-template","views-thymeleaf", "serialization-jackson","validation"]
  }]
}
